services:
  main:
    image: discord-bot:lasted
    container_name: discordbot-main
    build: .
    volumes:
      - ./jobs:/app/jobs
      - ./users_id:/app/users_id
    environment:
      - TZ=Asia/Bangkok